Safe get light
To fix an issue where Group would no longer toggle

```
TypeError: light.setPower is not a function
   at LightLibrary.self._setLightPower (/usr/src/app/light_library.js:59:9)
   at LightLibrary.self.setLightPowerOn (/usr/src/app/light_library.js:50:8)
   at LifxAdapter.self.lightsOn (/usr/src/app/lifx_adapter.js:77:22)
   at BulbManager.lightsOn (/usr/src/app/bulb_manager.js:38:19)
   at BulbManager.toggle (/usr/src/app/bulb_manager.js:29:8)
   at Controller.toggle (/usr/src/app/controller.js:20:22)
   at /usr/src/app/index.js:96:13
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
```